server:
  port: 8763
spring:
  application:
    name: nacos-feign

  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
        port: 8719
feign:
  sentinel:
    enabled: true


